# quarto version:
# https://github.com/quarto-dev/quarto-cli/releases/tag/v1.7.30

project:
  type: book

execute:
  error: true
  warning: false     # Hide warnings
  #output: false

book:
  title: "Getting started with Python for MIKE+"
  author:
    - "Ryan Murray"
    - "Rocco Palmitessa"
  date: "2025-05-15"

  url: https://dhi.github.io/getting-started-with-python-for-mike-plus/

  comments:
    giscus:
      repo: dhi/getting-started-with-python-for-mike-plus

  sidebar:
    logo: images/logos/DHI_Logo_Pos_RGB_noMargin.png

  chapters:
    - index.qmd

    - part: "Module 1 - Foundations"
      chapters:
        - module1_foundations/index.qmd
        - module1_foundations/github.qmd
        - module1_foundations/python_management.qmd
        - module1_foundations/ide.qmd
        - module1_foundations/python_scripts.qmd
        - module1_foundations/jupyter_notebooks.qmd
        - module1_foundations/python_basics.qmd
        - module1_foundations/llm_coding.qmd
        - module1_foundations/scientific_python.qmd
        - module1_foundations/homework.qmd

    - part: "Module 2 - Time Series"
      chapters:
       - module2_time_series/index.qmd
       - module2_time_series/01_mikeio.qmd
       - module2_time_series/02_reading_dfs0.qmd
       - module2_time_series/03_data_selection.qmd
       - module2_time_series/04_resampling.qmd
       - module2_time_series/05_visualization.qmd
       - module2_time_series/06_data_cleaning.qmd
       - module2_time_series/07_writing_dfs0.qmd
       - module2_time_series/homework.qmd

    - part: "Module 3 - Network Results"
      chapters:
       - module3_network_results/index.qmd
       - module3_network_results/01_overview_mikeio1d.qmd
       - module3_network_results/02_reading_network_files.qmd
       - module3_network_results/03_exploring_network_and_results.qmd
       - module3_network_results/04_selecting_network_data.qmd
       - module3_network_results/homework.qmd

    - part: "Module 4 - Calibration Plots and Statistics"
      chapters:
       - module4_calibration_plots_and_statistics\index.qmd
       - module4_calibration_plots_and_statistics\01_intro_modelskill.qmd
       - module4_calibration_plots_and_statistics\02_preparing_data.qmd
       - module4_calibration_plots_and_statistics\03_matching_data.qmd
       - module4_calibration_plots_and_statistics\04_visualizing_performance.qmd
       - module4_calibration_plots_and_statistics\05_quantifying_performance.qmd
       - module4_calibration_plots_and_statistics\homework.qmd

    - part: "Module 5 - MIKE+Py"
      #chapters:
      #  - module5_mikepluspy\index.qmd

    - part: "Module 6 - Putting Everything Together"
      #chapters:
      #  - module6_putting_everything_together\index.qmd

  page-footer: "Copyright 2025, DHI Group"

format:
  html:
    comments:
      giscus:
        repo: dhi/getting-started-with-python-for-mike-plus
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc-depth: 4
    toc-expand: false
  #pdf:
  #  documentclass: scrreprt